name: CI - Build/Test/Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build e Teste da API Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalação do JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Permissão para o Maven Wrapper
        run: chmod +x mvnw

      - name: Build com Maven
        run: ./mvnw clean package

      - name: Executar testes
        run: ./mvnw test

      - name: Build da imagem Docker
        run: docker build -t devops-api .
